-- Insert artists
INSERT INTO Artist (name) VALUES ('The Beatles');  -- Artist ID 1
INSERT INTO Artist (name) VALUES ('Pink Floyd');  -- Artist ID 2
INSERT INTO Artist (name) VALUES ('Led Zeppelin');  -- Artist ID 3

-- Insert albums (each album is linked to an artist)
INSERT INTO Album (title, artist_id) VALUES ('Abbey Road', 1);  -- Album ID 1 (The Beatles)
INSERT INTO Album (title, artist_id) VALUES ('The Wall', 2);  -- Album ID 2 (Pink Floyd)
INSERT INTO Album (title, artist_id) VALUES ('Dark Side of the Moon', 2);  -- Album ID 3 (Pink Floyd)
INSERT INTO Album (title, artist_id) VALUES ('Led Zeppelin IV', 3);  -- Album ID 4 (Led Zeppelin)
INSERT INTO Album (title, artist_id) VALUES ('Revolver', 1);  -- Album ID 5 (The Beatles)

-- Insert genres
INSERT INTO Genre (name) VALUES ('Rock');  -- Genre ID 1
INSERT INTO Genre (name) VALUES ('Progressive Rock');  -- Genre ID 2
INSERT INTO Genre (name) VALUES ('Hard Rock');  -- Genre ID 3
INSERT INTO Genre (name) VALUES ('Psychedelic Rock');  -- Genre ID 4
INSERT INTO Genre (name) VALUES ('Classic Rock');  -- Genre ID 5

-- Insert tracks (each track is linked to an album and a genre)
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Come Together', 259, 5, 1000, 1, 1);  -- Abbey Road, Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Something', 183, 5, 850, 1, 1);  -- Abbey Road, Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Another Brick in the Wall', 210, 5, 1200, 2, 2);  -- The Wall, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Comfortably Numb', 384, 5, 1400, 2, 2);  -- The Wall, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Money', 382, 4, 900, 3, 2);  -- Dark Side of the Moon, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Time', 413, 5, 1100, 3, 2);  -- Dark Side of the Moon, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Stairway to Heaven', 482, 5, 1500, 4, 3);  -- Led Zeppelin IV, Hard Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Black Dog', 296, 4, 950, 4, 3);  -- Led Zeppelin IV, Hard Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Eleanor Rigby', 138, 5, 1050, 5, 4);  -- Revolver, Psychedelic Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Yellow Submarine', 162, 4, 800, 5, 4);  -- Revolver, Psychedelic Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Hey You', 283, 5, 980, 2, 2);  -- The Wall, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Us and Them', 462, 4, 860, 3, 2);  -- Dark Side of the Moon, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('The Battle of Evermore', 348, 5, 670, 4, 3);  -- Led Zeppelin IV, Hard Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('She Loves You', 140, 4, 720, 5, 4);  -- Revolver, Psychedelic Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Helter Skelter', 258, 5, 940, 5, 4);  -- Revolver, Psychedelic Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Wish You Were Here', 334, 5, 1320, 3, 2);  -- Dark Side of the Moon, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Brain Damage', 230, 4, 790, 3, 2);  -- Dark Side of the Moon, Progressive Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('Tangerine', 176, 4, 560, 4, 3);  -- Led Zeppelin IV, Hard Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('I Want You (She’s So Heavy)', 467, 5, 1020, 1, 5);  -- Abbey Road, Classic Rock
INSERT INTO Track (title, len, rating, count, album_id, genre_id) 
VALUES ('While My Guitar Gently Weeps', 285, 5, 990, 1, 5);  -- Abbey Road, Classic Rock

-- GENERATED BY CHAT-GPT